[package]
name = "centaurus_port"
version = "0.1.0"
authors = ["mischief901 <alexmisch901@gmail.com>"]
edition = "2018"

[lib]
name = "centaurus_port"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
centaurus_common = { path = "../centaurus_common" }
