[package]
name = "centaurus"
version = "0.1.0"
authors = ["mischief901 <alexmisch901@gmail.com>"]
edition = "2018"

[lib]
name = "centaurus"
path = "src/conn.rs"
crate-type = ["dylib"]

[dependencies]
err-derive = "0.2.2"
lazy_static = "1.0"
tokio = { version = "0.2", features = ["full"] }
quinn = "0.5.3"
quinn-proto = "0.5.2"
rustler = "0.21.0"
futures = "0.3.1"

