[package]
name = "centaurus"
version = "0.1.0"
authors = ["mischief901 <alexmisch901@gmail.com>"]
edition = "2018"

[lib]
name = "centaurus"
path = "src/interface.rs"
crate-type = ["dylib"]

[dependencies]
rustler = { git="https://github.com/rusterlium/rustler.git" }
serde = { version = "1.0.104", features = ["derive"] }
serde_rustler = { git="https://github.com/mischief901/serde_rustler.git" }
lazy_static = "1.0"


